# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=25)),
                ('course_description', models.CharField(max_length=200)),
                ('course_syllabus', models.CharField(max_length=200)),
                ('course_schedule_date', models.DateField()),
                ('course_announcement', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='er_events', to='swift.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=20)),
                ('exam_details', models.CharField(max_length=250)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_courses', to='swift.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_value', models.CharField(max_length=2)),
                ('grade_comment', models.CharField(max_length=200)),
                ('grade_attendance', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_courses', to='swift.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_name', models.CharField(max_length=20)),
                ('invoice_description', models.CharField(max_length=200)),
                ('invoice_due_date', models.DateField()),
                ('invoice_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=5)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_value', models.IntegerField()),
                ('marks_feedback', models.CharField(max_length=250)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_courses', to='swift.Course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_exams', to='swift.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=25)),
                ('parent_address', models.CharField(max_length=250)),
                ('parent_phone', models.CharField(max_length=12)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_logins', to='swift.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=25)),
                ('student_address', models.CharField(max_length=250)),
                ('student_phone', models.CharField(max_length=12)),
                ('student_class_grade', models.CharField(max_length=10)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_logins', to='swift.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_parents', to='swift.Parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_students', to='swift.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=25)),
                ('teacher_address', models.CharField(max_length=250)),
                ('teacher_phone', models.CharField(max_length=12)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_logins', to='swift.Login')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_students', to='swift.Student'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoivce_parents', to='swift.Parent'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_students', to='swift.Student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_students', to='swift.Student'),
        ),
        migrations.AddField(
            model_name='event_registration',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='er_parents', to='swift.Parent'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teachers', to='swift.Teacher'),
        ),
    ]
